tunnel: a5a62e01-d933-4dd4-95fb-8230ccd26988
credentials-file: /Users/ekowibowo/.cloudflared/a5a62e01-d933-4dd4-95fb-8230ccd26988.json

ingress:
  # Single hostname handles both HTTP API and WebSocket upgrade
  - hostname: access.remoteworker.id
    service: http://localhost:3003
  - service: http_status:404